name: Express App CI/CD

on:
  push:
    branches:
      - main
    paths:
      - "express-app/**"
      - ".github/workflows/express-app.yml"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: "16"

    - name: Install Dependencies
      run: npm install

    - name: Build Docker Image
      run: docker build -t siddarthal/githubactions:latest .

    - name: Push Docker Image
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
      run: docker push siddarthal/githubactions:latest
