version: "3.8"
services:
  db:
    image: postgres:13.2-alpine
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DATABASE: postgres
    networks:
      - database-network
    volumes:
      - ./database:/var/lib/postgresql/data
networks:
  database-network:
    external: true
    name: star-link
