version: '3'
services:
  backendimg:
    image: backend:l1
    environment:
      -  REQUEST_ORIGIN: ip
      -  REDIS_HOST: cache-service
      -	 POSTGRES_HOST: db
      -	 POSTGRES_USER: postgres
      -	 POSTGRES_PASSWORD: postgres
      -	 POSTGRES_DATABASE: postgres
    networks:
      - backend
    # ports:
    #   - 8080:8080
networks:
  backend:
    external: true
    name: star-link