FROM ubuntu:latest AS BUILD_IMAGE 
RUN apt update && apt install wget unzip -y 
RUN wget https://www.tooplate.com/zip-templates/2096_individual.zip
RUN unzip 2096_individual.zip && cd 2096_individual && tar -czf individual.tgz * && mv individual.tgz /root/individual.tgz
FROM ubuntu:latest
RUN apt update && apt install apache2 git wget -y 
COPY --from=BUILD_IMAGE /root/individual.tgz /var/www/html 
RUN cd /var/www/html/ && tar xzf individual.tgz 
CMD ["/usr/sbin/apache2ctl","-D", "FOREGROUND"] 
VOLUME /var/log/apache2
WORKDIR /var/www/html/
EXPOSE 80