version: '3.8'
services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - nginx_net
    ports:
      - 80:80
networks:
  nginx_net:
    external: true
    name: star-link
